CLASS zcl_lab_39_budget DEFINITION ABSTRACT
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.

  METHODS GET_BUDGET ABSTRACT RETURNING VALUE(rv_budget) TYPE STRING.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_39_budget IMPLEMENTATION.
ENDCLASS.
