CLASS zcl_lab_46_mobile_operator DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
   CLASS-EVENTS NEW_CALL EXPORTING VALUE(EV_PHONE_NUMBER) TYPE STRING.
   CLASS-METHODS ASSIGN_CALL.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_lab_46_mobile_operator IMPLEMENTATION.
  METHOD assign_call.
   RAISE EVENT NEW_CALL EXPORTING EV_PHONE_NUMBER = '1234567'.
  ENDMETHOD.

ENDCLASS.
